import type { Metadata } from 'next';
import './globals.css';
import { FetchDataProvider } from './FetchDataProvider';

export const metadata: Metadata = {
  title: 'Yah Dun Kno!',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <FetchDataProvider>{children}</FetchDataProvider>
      </body>
    </html>
  );
}
