export const landingMetaData = [
  {
    youtubeId: 'GoGUaUHdrKQ',
    title: 'easy-linguistics-radio-sign-lang-island',
    dueSentences: 153,
    dueSnippets: 225,
    dueWords: 55,
    contentHasBeenReviews: true,
  },
  {
    youtubeId: 'jAYBfCKXgEE',
    title: 'coten-radio-mental-health-part-two',
    dueSentences: 13,
    dueSnippets: 18,
    dueWords: 38,
    contentHasBeenReviews: true,
  },
  {
    youtubeId: 'Zr0okDceDig',
    title: 'Toru-Miyamoto-Japanese-communist-youth',
    dueSentences: 8,
    dueSnippets: 2,
    dueWords: 12,
    contentHasBeenReviews: true,
  },
  {
    youtubeId: '6KuWUthhBnU',
    title: 'Toru-Miyamoto-Takaichis-risky-remarks-Taiwan-emergency',
    dueSentences: 5,
    dueSnippets: 3,
    dueWords: 17,
    contentHasBeenReviews: true,
  },
  {
    youtubeId: 'eEGmmzm3wwY',
    title: 'koten-radio-saicho-kukai-enlighten-men',
    dueSentences: 2,
    dueSnippets: 2,
    dueWords: 9,
    contentHasBeenReviews: true,
  },
  {
    youtubeId: 'V561Pg7u_78',
    title: 'Takasugi-Shinsaku-destroying-feudal-society',
    dueSentences: 0,
    dueSnippets: 2,
    dueWords: 14,
    contentHasBeenReviews: true,
  },
  {
    youtubeId: 'DaCmjtB-5To',
    title: 'jaru-jaru-push-pull-door',
    dueSentences: 0,
    dueSnippets: 0,
    dueWords: 3,
    contentHasBeenReviews: true,
  },
];
